@include('UI.components/home_slider')  
<div class="block-space block-space--layout--divider-sm"></div>
<div class="container">
   	<div class="row">
	   	<div class="col-md-10 offset-md-1">
	   	  	<div class="privacy">
	   	  	    <h1>Terms And Conditions</h1>
		    	<p>This document is an electronic record in terms of Information Technology Act, 2000 and rules
				there under as applicable and the amended provisions pertaining to electronic records in various
				statutes as amended by the Information Technology Act, 2000. This electronic record is
				generated by a computer system and does not require any physical or digital signatures.
				This document is published in accordance with the provisions of Rule 3 (1) of the Information
				Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and
				regulations, privacy policy and Terms of Use for access or usage of www.drhelpdesk.in website
				and its mobile applications.</p>
				<h6>1. General</h6>
				<p>www.drhelpdesk.in, an internet based portal and “DrHelpDesk” a mobile application, (hereinafter
				together be referred to as “Website") is operated by Aensa Health Solutions Private Limited
				(hereinafter to be referred as “Company” or “We” or “Our” or “Us”), a company duly incorporated
				under the provisions of the Companies Act, 2013.</p>
				<p>Use of the Website is offered to You, subject to acceptance of all the terms, conditions and notices
				contained in these Terms including applicable policies which are incorporated herein by reference,
				along with any amendments / modifications made by Company at its sole discretion and posted on
				the Website, including by way of imposing an additional charge for access to or use of a service(s).
				For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean
				any natural or legal person who has agreed to become a buyer on the Website by providing Account
				Information (defined below) while registering on the Website as a registered User using the
				computer systems.</p>
				<p>Company shall not be required to notify You, whether as a registered user or not, of any changes
				made to the Terms and Conditions ("Terms"). The revised Terms shall be made available on the
				Website. Your use of the Website and the Services is subject to the most current version of the Terms
				made available on the Website, at the time of such use. You are requested to regularly visit the
				Website to view the most current Terms. It shall be your responsibility to check the Terms
				periodically for changes. Company may require You to provide Your consent to the updated Terms in
				a specified manner prior to any further use of the Website and the Services, provided on the
				Website. If no such separate consent is sought, Your continued use of the Website, following changes
				to the Terms, will constitute your express acceptance of those changes.</p>
				<p>By (i) using this Website or any facility or service provided by this Website in any way; or (ii) merely
				browsing the Website, You agree that you have read, understood and agreed to be bound by,
				including without limitation, these Terms, the Website's Privacy Policy. and such other rules, guidelines, policies, terms and conditions as are relevant under the applicable law(s) in India and
				other jurisdictions for the purposes of accessing, browsing or transacting on the Website, or availing
				any of the Services, and such rules, guidelines, policies, terms and conditions shall be deemed to be
				incorporated into, and considered as part and parcel of these Terms of Use</p>
				<p>The User agrees to use the service to authorise the Company to provide an individual who shall act
				in the capacity as the agent of the User and get the products requested by the User from the third
				party on the Users behalf.</p>
				<p>The scope of offering the services of the Company to facilitate pick up/collection services for any
				service requested or products requested to be purchased by the User shall only be in certain
				geographies located in India and shall never be for any locations outside India.</p>
				<h6>2. Products and Services</h6>
				<p>The Website is a platform that facilitates the online requisition by the user for purchase of medicines
				and wellness / health related products and services offered by Company's various registered thirdparty/ies (third-parties shall for the purpose of this Terms, include without limitation third party
				licensed retail pharmacies, third-party labs) ("Products and Services"). The sale & purchase /
				transaction between the registered third-parties and You, of Products and Services, facilitated by the
				requisition placed by You on the Website shall be governed by these Terms. Company is not and
				cannot be a party to or save as except as may be provided in these Terms of Use, control in any
				manner, any transaction between You and the third-parties.</p>
				<p>Company further reserves the right to change or modify these Terms of Use or any policy or
				guidelines of the Website including the Privacy Policy, at any time and in its sole discretion. Any
				changes or modifications made will be effective immediately upon posting the revisions on the
				Website and You waive any right You may have to receive specific notice of such changes or
				modifications. Your continued use of the Website will confirm Your acceptance of such changes or
				modifications.</p>
				<h6>o Technology Platform for Pharmaceutical Products –</h6>
				<p>–Company facilitates the purchase of drugs
				and other pharmaceutical products and services (which shall also include OTC and wellness
				products) offered by third-party licensed retail pharmacies (“licensed Retail Pharmacies or Third
				Party Pharmacies”). The Company and the Website merely provide hosting services to You and persons browsing/ visiting the Website. All items offered for sale on the Website, and the content
				made available by the licensed Retail Pharmacies, are third party user generated contents and third
				party products. The Company has no control over such third party user generated contents and/
				Pharmaceutical Goods and Services and does not originate or initiate the transmission, or select the
				sender/recipient of the transmission, or the information contained in such transmission. The quality
				of the Pharmaceutical Goods and Services made available by the licensed Retail Pharmacies through
				the Website shall be the sole responsibility of the licensed Retail Pharmacies. The Company shall
				have no liability with respect to the authenticity of the Pharmaceutical Goods and Services being
				facilitated through the Website.</p>
				<p>The Company does not take any representation or warranty as to legal title of the Pharmaceutical
				Goods and Services offered for sale by the licensed Retail Pharmacies on the Website. The right, title,
				claim or interest in the products sold through the Website shall not vest with the Company and the
				Company shall not have any obligations or liabilities in respect of any transactions on the Website.
				The Company is not responsible for delayed, non-performance or breach of contract entered into
				between You and the third-party for purchase and sale of goods or services offered by such Third
				Party Pharmacies on the Website; The Company gives no guarantee that the concerned third-party pharmacies will perform any transaction concluded on the Website. The Company is not responsible
				for the Pharmaceutical Goods and Services which are out of stock, back ordered or otherwise
				unavailable, but were shown as available on the Website at the time of placement of order by You.
				Content: You agree and acknowledge that the respective third-party pharmacies are exhibiting Third
				Party Content which includes catalogue of drugs/ pharmaceutical products or services, and
				information in relation to such drugs/ pharmaceutical products or services, on the Website. The
				content available on the Website, including without limitation, text, copy, audio, video graphics etc is
				for general information purposes only and does not constitute either an advertisement or promotion
				of any drug being offered for sale by the third-party pharmacies on the Website or any professional
				medical advice, diagnosis, treatment or recommendation of  any kind. Further, the Company shall not
				be responsible for ensuring that the content made available are not misleading and describe the
				actual condition of the Pharmaceutical Goods and Services. Also, You acknowledge and understand that the Company provides no warranty or representation with respect to the authenticity of the
				information provided on the Website and You must do Your own check.
				The Company shall not be, in any event, held responsible or liable for any damages arising out of
				such content by third-parties</p>
				<h6>Prescription Drugs</h6>
				<p>In order to purchase drugs and pharmaceutical products that requires a valid
				prescription, You are required to upload a scanned copy of the valid prescription via email, or on the
				Website or any other digital platform of the Company. Third- Party Pharmacies will verify the
				prescription forwarded by You and in case of any discrepancy observed by the Third-Party
				Pharmacies, the order will not be processed and be cancelled by the third-party pharmacies
				immediately. You are also required to make the original prescription available at the time of receipt
				of the order as per the conditions laid down by the Third-Party pharmacies. You shall also allow the
				User’s Agent to offer, on your behalf, the right to get stamped, the original prescription at the time of
				receipt of medicine. It is clarified that User’s Agent shall mean the individual agent offering services
				as an agent of the User, acting for and behalf of r of the User for the purpose of procuring the
				requisitioned medicines through the process of collecting the medicines ordered by the User with
				the User’s consent from the Licensed Retail Pharmacies.
				</p>
				<h6>Substitution of Prescribed Drugs</h6>
				<p>You acknowledge and accept that the order for a substitute of a
				Prescription Drug would only be processed if the medical expert/ doctor has himself/ herself
				permitted for any other equivalent generic drug to be dispensed in place of the Prescription Drug in
				the prescription or if the prescription solely lists the salt names instead of a specific brand name.
				You further acknowledge and accept that, in the absence of the above, the concerned Third Party
				Pharmacy would not dispense a substitute drug in place of the Prescription Drug.</p>
				<h6>Invitation to offer for sale -</h6>
				<p>The listing of drugs and other pharmaceutical products on the Website
				by the Third Party Pharmacies is merely an ‘invitation to an offer for sale’ and not an ‘offer for sale’.
				The placement of an order by You shall constitute an offer by You to enter into an agreement with
				the Third Party Pharmacies (“Offer”). Post the Offer from the Third Party Pharmacies, the Company
				shall send an email to You with the information on the Offer along with the details of the concerned
				Third Party Pharmacy(s) who may undertake the sale, and such an email shall not be considered as an acceptance of the Offer. The acceptance of the Offer would only be undertaken by the Third Party
				Pharmacy(s) after the validation/ verification of the prescription by such Third Party Pharmacy (in
				case of Prescription Drugs) and the ascertainment of the available stock in the relevant Third Party
				Pharmacy(s) (in the case of prescription as well as other drugs/ pharmaceutical products), by way of
				a confirmatory email to be sent to You.</p>
				<p>It is hereby clarified that any reference of the term ‘offer/ offered for sale by the licensed Retail
				Pharmacies’, as appearing in these Terms of Use, shall be construed solely as an ‘invitation to offer
				for sale’ by any such licensed Retail Pharmacies.</p>
				<h6>Transfer of Property and Completion of Sale</h6>
				<p>Upon acceptance of the Offer by the concerned
				licensed Retail Pharmacies (being the brick and mortar pharmacy, the Pharmaceutical Drugs and
				Services would be dispensed at the pharmacy, in accordance with the terms of the order placed by
				You. Such dispensation shall also take place under the direct/ personal supervision of the
				pharmacist of the licensed Retail Pharmacies, wherever required under the applicable law(s).</p>
				<p>You agree and acknowledge that the property and title in the Pharmaceutical Drugs and Services
				ordered by You shall stand immediately transferred to You upon the dispensation of Pharmaceutical
				Drugs and Services and the raising of the invoice at the concerned licensed Retail Pharmacies.
				Accordingly, the sale of Pharmaceutical Drugs and Services is concluded at the concerned licensed
				Retail Pharmacies itself.</p>
				<p>The invoice in relation to the Pharmaceutical Drugs and Services, that are required to be delivered to
				You shall be issued by the concerned licensed Retail Pharmacies (being the brick and mortar
				pharmacy) which is to process and satisfy the order for such Pharmaceutical Drugs and Services.</p>
				<h6>Selling of Drugs</h6>
				<p>The Pharmaceutical Drugs shall be displayed, exhibited, offered for sale or sale /
				sold by the Licensed Retail Pharmacies to the Users and not by the Company in any manner
				whatsoever. User accepts and acknowledges that the User’s Agent shall be responsible to collect the
				medicines ordered by User from the Licensed Retail Pharmacy and to carry it to the address notified
				by User, with no control over the Pharmaceutical Drugs displayed, exhibited, offered for sale or sale
				/ sold by the Licensed Retail Pharmacies and that the there is no direct or indirect liability of the
				Company and/or User’s Agent and there is no additional obligation on the Company and / or User’s Agent apart from collection of medicines for the User and that the Company and / or User’s Agent
				assumes no vicarious liability of any form or nature whatsoever. User further agrees and
				acknowledges that the User’s Agent acts as the agent of the User for collecting the medicines from
				the Licensed Retail Pharmacy. The aforementioned services are being undertaken by Users’ Agent
				with Users’ consent and therefore the Company is merely facilitating for the User and Users’ Agent to
				connect. The Users’ Agent is independently offering pick-up and collection services and in no event
				shall the Company be responsible and liable for the act of the Users’ Agent’s including acts of
				omissions or commissions while carrying out its obligation</p>
				<h6>Diagnostics Services</h6>
				<p>The Company provides Services through the Website as a marketplace and
				facilitates the Users to avail diagnostic test/ package facilities offered by third-party labs (“Labs”)
				through the Website. Further, the Company shall in no event be responsible for the samples
				collected, tests conducted and reports generated by the third-party labs. The Company only provides
				facilitation services to the Users of the Website. User and the Labs agree to use the Website and the
				materials provided therein only for purposes that are permitted by: (a) these Terms of Use; and (b)
				any applicable law(s), regulation or generally accepted practices or guidelines in the relevant
				jurisdictions.</p>
				<p>Notwithstanding anything to the contrary contained herein, Labs alone shall be liable for Labs’
				dealings and interaction with the Users who avail the services of the Labs or diagnostic centres
				contacted or managed through the Website and the Company shall have no liability or responsibility
				in this regard. The Company does not guarantee or make any representation with respect to the
				correctness, completeness or accuracy of the information or details provided by such User, Labs or
				any diagnostic centre or any third party through the Website. The Company, upon its discretion, may
				suspend labs or Users ability to use or access the Website at any time when the Company observes
				breach of these Terms of Use or for any other reason. The Company shall have no liability or
				responsibility towards any wrong information on the Website with regard to the Labs.</p>
				<p>Please note that DrHelpDesk has tied-up with 3rd party Labs for conducting diagnostics services.</p>
				<p>The said Labs are NABL, CAP or ISO certified and therefore assure the accuracy and completeness of
				the collection of samples, examination and issuance of pathology report. The lab takes ownership of 
				all the reports handed over to the patient.</p>
				<p>We do not take any responsibility for the consequences arising out of the aforementioned. The
				absence of any information and/or warning pertaining to the diagnostics services shall not be
				considered and assumed as an implied assurance of the Company. These terms and conditions for
				Free Home Sample Pick Up ("Offer Terms") are in addition to the Terms & Conditions, mentioned
				herein, to which you agree to by using DrHelpDesk. In the event of any conflict between the
				Conditions of Use & Sale and these Offer Terms, these Offer Terms will prevail, only for the purposes
				of this Offer. Free Home Sample Pick Up service is contingent on minimum cart-order value
				(“Threshold Amount”), which is the eligibility criteria for an order to qualify for Free Home Sample
				Pick Up service. Threshold Amount is dynamic in nature and can be increased/decreased by
				DrHelpDesk, in its sole discretion without any prior notice. Customers whose cart-order value
				exceeds the Threshold Amount will be eligible for Free Home Sample Pick Up. For any diagnostics
				order having a cart-order value less than or equal to Threshold Amount will be charged a Sample
				Pick Up Fee which shall be dynamic in nature and shall be contingent upon factors, including but not
				limited to, delivery/pick-up address, Threshold Amount etc. Sample Pick Up Fee & Threshold
				Amount shall be calculated by an algorithm which shall be based on variables decided at the sole
				discretion of the Company. DrHelpDesk reserves the right to discontinue/modify/change the
				Threshold Amount at any time without prior notice. Notwithstanding anything contained herein
				Threshold Amount reflected in the cart at the time of checkout shall be considered final & binding.
				Please also note that Free Home Sample Pick Up service threshold is determined by the final cart
				value after any promotional code has been deducted. Final Sample Pick Up Fee shall be displayed at
				the checkout pages. The purchase of the product(s) and services will be governed by the Terms &
				Conditions, mentioned herein, on the DrHelpDesk portal. The Offer is subject to laws of India. The
				courts at Mumbai shall have the exclusive jurisdiction in respect of any disputes or any matter
				arising out of this Offer.</p>
				<h6> Online Doctor Consultancy</h6>
				<p>The Company is a facilitator of healthcare services that provides
				healthcare products and services to the Users. The words “Your Physician” or “Your Doctor” or
				“Healthcare Provider” or similar words on the Website, shall be interpreted and mean the User’s 
				personal doctor with whom the User has a doctor-patient relationship. The third party registered
				medical practitioners are not related to Company but merely providing medical consultation to You
				with Your consent. You agree and acknowledge that the third party registered medical practitioners
				are independent contractors and hence, the Company, in no event, shall be directly or vicariously
				liable for any advice or medical consultancy or any loss arising from the third party registered
				medical practitioners.</p>
				<p>The e-prescription which may be issued by the registered medical practitioner (s), in certain events,
				may not be a valid prescription under applicable law(s) of India and may not be used for
				dispensation of medicines by any pharmacist including the third-party licensed retail pharmacies.
				We will only act as an aggregator in the event You request Us to process the e-prescription or any
				form thereof (whether original or scanned copy of the original prescription). We will have no
				responsibility or liability in such events. You agree and acknowledge that it shall be at your sole
				responsibility and risk.</p>
				<p>The Company does not recommend any specific registered medical practitioner(s), tests, products,
				opinions or other information that may be mentioned in the Website. Reliance on any information
				provided on the Website is solely at Your own risk. You shall call Your nearest doctor/hospital or
				any related helpline in case of any medical emergency.
				The Services are not for use in medical emergencies or for critical health situations and may not be
				best solution where a face-to-face consultation is required. Hence, we discourage any delay in
				seeking advice from Your doctor on account of something that You may have heard/viewed on the
				Website</p>	
				<p>Further, the Company shall not it is Your responsibility for ensuring that the information submitted
				is accurate and the Company shall not make any effort to validate any information provided by You
				for using the Services with respect to content,</p>	
				<p>The opinions, statements, consultation via digital mode provided by the third party registered
				medical practitioners through the Website shall not reflect the opinions of the Company, its affiliates
				etc. The Company makes no warranty that the Services will meet Your requirements, or that the
				Service(s) will be uninterrupted, timely, secure, or error free. This includes loss of data or any 
				service interruption caused by the Company employees. The Company is not responsible for
				transmission errors, corruption of data</p>
				<h6>3. Eligibility of Use</h6>
				<p>Use of the Website is available only to persons who can form legally binding contracts under Indian
				Contract Act, 1872. Persons who are "incompetent to contract" within the meaning of the Indian
				Contract Act, 1872 including without limitation minors, un-discharged insolvents etc. are not eligible
				to use the Website. The Products shall also not available to any Users suspended or removed from
				the company’s system for any reason whatsoever. If You do not conform to the above qualification,
				You will not be permitted to put a requisition for the Products through the Website. By accessing and
				using this Website, You represent that You are of legal age to form a binding contract and are not a
				person barred from receiving services under the laws as applicable in India. Notwithstanding the
				foregoing, if You are below the age of eighteen (18) years, You may avail the services provided by the
				Website, through Your legal guardian in accordance with the applicable laws.
				Company reserves the right to terminate your membership and / or refuse to provide you with
				access to the Website if it is brought to Company’s notice or if it is discovered that you are under the
				age of 18 years.</p>
				<p>Company reserves the right to refuse access to use the services offered at the Website to new Users
				or to terminate access granted to existing Users at any time without according any reasons for doing
				so and You shall have no right to object to the same</p>
				<p>You shall not have more than one active Account on the Website. Additionally, You are prohibited
                from selling, trading, or otherwise transferring Your Account to another party</p>
                <h6>6. User Obligations</h6>
                <p>Subject to compliance with these Terms, Company grants You a personal, non-exclusive, nontransferable, limited privilege to access and use this Website and the services provided herein.
				You agree to use the services, Website and the materials provided therein only for purposes that are
				permitted by: (a) the Terms; and (b) any applicable law, regulation or generally accepted practices
				or guidelines in the relevant jurisdictions.</p>
				<p>You agree to adhere to all limitations on dissemination, use and reproduction of any materials (such
				as the Product catalogues) that You access on the Website in accordance with Section 7 below.
				You agree not to access (or attempt to access) the Website and the materials or services by any
				means other than through the interface that is provided by Company. You shall not use any deeplink, robot, spider or other automatic device, program, algorithm or methodology, or any similar or
				equivalent manual process, to access, acquire, copy or monitor any portion of the Website or Content (as defined below), or in any way reproduce or circumvent the navigational structure or
				presentation of the Website, materials or any Content, to obtain or attempt to obtain any materials,
				documents or information through any means not specifically made available through the Website.
				You acknowledge and agree that by accessing or using the Website or Services, You may be exposed
				to content from other users that You may consider offensive, indecent or otherwise objectionable.
				Company disclaims all liabilities arising in relation to such offensive content on the Website. Further,
				You may report such offensive content in the manner prescribed herein.</p>
				<p>If Website allows You to post and upload any material on the Website, You hereby undertake to
				ensure that such material is not offensive and in accordance with applicable laws. Further, You
				undertake not to:</p>
				<p>Defame, abuse, harass, threaten or otherwise violate the legal rights of others;</p>
				<p>Impersonate any person or entity, or falsely state or otherwise misrepresent Your affiliation with a person or entity;</p>
				<p>Publish, post, upload, distribute or disseminate any inappropriate, profane, defamatory, infringing,
				obscene, indecent or unlawful topic, name, material or information through any bookmark, tag or
				keyword</p>
				<p>Upload files that contain software or other material protected by applicable intellectual property
                laws unless You own or control the rights thereto or have received all necessary consents;</p>
                <p>Upload or distribute files that contain viruses, corrupted files, or any other similar software or programs that may damage the operation of the Website or another's computer;</p>
                <p>Engage in any activity that interferes with or disrupts access to the Website or the services (or the servers and networks which are connected to the Website);</p>
                <p>Attempt to gain unauthorized access to any portion or feature of the Website, any other systems or
				networks connected to the Website, to any Company server, or to any of the services offered on or
				through the Website, by hacking, password mining or any other illegitimate means;</p>
				<p>Probe, scan or test the vulnerability of the Website or any network connected to the Website, nor
				breach the security or authentication measures on the Website or any network connected to the
				Website. You may not reverse look-up, trace or seek to trace any information on any other user, of or visitor to, the Website, or any other customer of Company, including any Company Account not
				owned by You, to its source, or exploit the Website or service or information made available or
				offered by or through the Website, in any way whether or not the purpose is to reveal any
				information, including but not limited to personal identification information, other than Your own
				information, as provided for by the Website;</p>
				<p>Disrupt or interfere with the security of, or otherwise cause harm to, the Website, systems resources,
				accounts, passwords, servers or networks connected to or accessible through the Websites or any
				affiliated or linked sites;</p>
				<p>Collect or store data about other users in connection with the prohibited conduct and activities set forth in this Section.</p>
				<p>Use any device or software to interfere or attempt to interfere with the proper working of the
				Website or any transaction being conducted on the Website, or with any other person's use of the
				Website;</p>
				<p>Use the Website or any material or Content for any purpose that is unlawful or prohibited by these
				Terms, or to solicit the performance of any illegal activity or other activity which infringes the rights
				of Company or other third parties;</p>
				<p>Conduct or forward surveys, contests, pyramid schemes or chain letters;</p>
				<p>Download any file posted by another user of a service that you know, or reasonably should know, cannot be legally distributed in such manner;</p>
				<p>Falsify or delete any author attributions, legal or other proper notices or proprietary designations or labels of the origin or source of software or other material contained in a file that is uploaded;</p>
				<p>Violate any code of conduct or other guidelines, which may be applicable for or to any particular Service;</p>
				<p>Violate any applicable laws or regulations for the time being in force within or outside India;</p>
				<p>Violate the Terms including but not limited to any applicable Additional Terms of the Website contained herein or elsewhere; and</p>
				<p>Reverse engineer, modify, copy, distribute, transmit, display, perform, reproduce, publish, license,
				create derivative works from, transfer, or sell any information or software obtained from the
				Website.</p>
				<p>Company has no obligation to monitor such communications by You. However, Company reserves
				the right to review materials posted by You and to remove any materials in its sole discretion.
				Company reserves the right to terminate the User's access to any or all of such communication
				services provided by Company at any time without notice for any reason whatsoever.
				Company reserves the right at all times to disclose any information as is necessary to satisfy or
				comply with any applicable law, regulation, legal process or governmental request, or to edit, refuse
				to post or to remove any information or materials, in whole or in part, in Company's sole discretion.
				Company does not control or endorse the content, messages or information found in any
				communication service and, therefore, Company specifically disclaims any liability or responsibility
				whatsoever with regard to the communication services and any actions resulting from the user's
				participation in any communication service.</p>
				<p>You agree that You are solely responsible to Company and to any third party for any breach of Your
				obligations under the Terms and for the consequences (including any loss or damage which
				company or its affiliates or its vendors may suffer) for any such breach</p>
				<p>You agree and acknowledge that Company is not the third party of the Products and Company shall
				in no manner be deemed to be the third party of the Products on this Website. Company is only
				facilitating purchase of the Products by You from the third parties by providing the services to You.
				You agree that Company may, at any time, modify or discontinue all or part of the Website, charge,
				modify or waive fees required to use the Website, or offer opportunities to some or all Website
				Users</p>
				<p>You agree that the Website may not be used for illegal purposes. The Information and Services may
				not be used for any illegal purpose. You may not access our networks, computers, or the Information
				and Services in any manner that could damage, disable, overburden, or impair them, or interfere
				with any other person's use and enjoyment. You may not attempt to gain unauthorized access to any
				Information or Services, other accounts, computer systems, or networks connected with the Website, the Information, or Services. Such unauthorized access includes, but is not limited to, using
				another person’s login credentials to access his or her Company profile/ account. Any attempt by
				any individual or entity to solicit login information of any other user or Medical Expert or to access
				any such account is an express and direct violation of these Terms of Use and of applicable law(s),
				including relevant privacy and security laws and laws prohibiting unfair or unethical business
				practices.</p>
				<p>You agree and acknowledge that the exchanges between the third party registered medical
				practitioners and the You over telephone and the e-prescription would be accessible to the Company
				for the purposes of monitoring the quality of the consultation. The consultation provided by the
				third-party registered medical practitioner shall be done vide a secured recorded line</p>
				<h6>Risks associated with Company’s Services</h6>
				<p>You abide by these Terms of Use, Privacy Policy and any other Company Policy by using the Company’s Services.</p>
				<p>The third party registered medical practitioners will not be examining You physically and may not
				have access to all or some of Your medical history that might be critical to consult You. The third
				party registered medical practitioners will not have the benefit of information that would be
				obtained by examining You in person, observing Your physical condition and by going through Your
				medical records. This means that the Services provided is different from the diagnostic and
				treatment services typically decided by a physician. Therefore, the third party registered medical
				practitioners may not be aware of facts or information that would affect his or her opinion of Your
				diagnosis. Therefore, to reduce the risk of this limitation, the Company strongly encourages You to
				be in touch with an on-ground physician and share the Company’s opinion with him/her.
				You acknowledge and agree, by requesting a medical opinion through the Website, that</p>
				<p>o the advice/information/opinion on diagnosis You may receive could be limited and provisional;</p>
				<p> the medical opinion is not intended to replace a face-to-face visit with a physician and it does replace an actual doctor-patient relationship;</p>
				<p>o in case of a second opinion where there is a difference of opinion among Our third party registered
				medical practitioners and Your physician, You would bear the responsibility to decide on online or
				offline consultation, or procedure, and/or treatment;</p>
				<p>the Medical Expert is reliant on information provided by You and hence any information
				demonstrated to have been falsified, misleading or incomplete will immediately render the opinion
				and all details therein null and void;</p>
				<p>in some events, the Medical Expert may determine that the transmitted information is of inadequate quality and may ask for more information, without which he/she may refuse to answer the query;</p>
				<p>in rare cases, the third party registered medical practitioners may feel that the query may not be
				answerable without physically examining the patient/ Users and the Consultation may be refused
				forthwith</p>
				<p>in very rare instances, security protocols could fail, causing a breach of privacy of personal medical information; and</p>
				<p>o delays in medical evaluation and answers could occur due to deficiencies or failures of the service as
                per those mentioned in these Terms of Use.</p>
                <h6>7. Use of Materials</h6>
                <p>Except as expressly indicated to the contrary in any applicable Additional Terms, Company hereby
				grants You a personal, non-exclusive, freely revocable (upon notice from Company), nontransferable access to view, download and print product catalogues or any other materials available
				on the Website, subject to the following condition:</p>
				<p>o You may access and use the materials solely for personal, informational, and internal purposes, in
				accordance with the Terms; You may not modify or alter Product catalogues or any other materials
				available on the Website;</p>
				<p>o You may not distribute or sell, rent, lease, license or otherwise make the Product catalogues or any other materials available on the Website available to others; and</p>
				<p>o You may not remove any text, copyright or other proprietary notices contained in the Product catalogues or any other materials available on the Website.</p>
				<p>The rights granted to You in the Product catalogues or any other materials as specified above are not
				applicable to the design, layout or look and feel of the Website. Such elements of the Website are 
				protected by intellectual property rights and may not be copied or imitated in whole or in part. The
				Product catalogues or any other materials available on the Website shall not be copied or
				retransmitted unless expressly permitted by Company</p>
				<p>Any software that is available on the Website is the property of Company or its third parties. You
				may not use, download or install any software available at the Website, unless otherwise expressly
				permitted by these Terms or by the express written permission of Company.</p>
				<p>Any purchase of the merchandise or Services from the Website will be strictly for personal use of the
				User. The User hereby expressly agrees that any merchandize or Services purchased by the User will
				not be sold, resold, bartered or in any way used for any commercial purposes or for profit. The User
				hereby acknowledges that the Services or merchandize purchased is not transferrable to any third
				party for profit.</p>
				<h6>8. Usage Conduct</h6>
				<p>You shall solely be responsible for maintaining the necessary computer equipments and Internet connections that may be required to access, use and transact on the Website</p>
				<p>You are also under an obligation to use this Website for reasonable and lawful purposes only, and shall not indulge in any activity that is not envisaged through the Website.</p>
				<p>You shall use this Website, and any voucher/ coupons purchased through it, for personal, noncommercial use only and shall not re-sell the same to any other person.</p>
				<p>Once you subscribe with DrHelpDesk, you shall use the prescription exclusively to purchase
				medicines via DrHelpDesk and shall not use the same prescription to fulfill the medicine
				requirement from other retailers until the medicines are not supplied for any reason via DrHelpDesk
				partner third parties.</p>
				<h6>9. Intellectual Property Rights</h6>
				<p>The Website and the processes, and their selection and arrangement, including but not limited to all
				text, graphics, user interfaces, visual interfaces, sounds and music (if any), artwork and computer
				code (collectively, the "Content") on the Website is owned and controlled by Company and the
				design, structure, selection, coordination, expression, look and feel and arrangement of such Content
				is protected by copyright, patent and trademark laws, and various other intellectual property rights.</p>
				<p>The trademarks, logos and service marks displayed on the Website ("Marks") are the property of
				Company or their third parties or respective third parties. You are not permitted to use the Marks
				without the prior consent of Company, the relevant third parties that may own the Marks.
				Unless otherwise indicated or anything contained to the contrary or any proprietary material owned
				by a third party and so expressly mentioned, Company owns all intellectual property rights to and
				into the trademark www.drhelpdesk.in, and the Website, including, without limitation, any and all
				rights, title and interest in and to copyright, related rights, patents, utility models, designs, knowhow, trade secrets and inventions (patent pending), goodwill, source code, meta tags, databases, text,
				content, graphics, icons, and hyperlinks</p>
				<p>Except as expressly provided herein, You acknowledge and agree that You shall not copy, republish,
				post, display, translate, transmit, reproduce or distribute any Content through any medium without
				obtaining the necessary authorization from Company or third party owner of such Content.</p>
				<h6>11. Third Party Content</h6>
				<p>The Website makes available general third party information such as, Product catalogues, lists of
				vendors, technology and features, advertisements including videos, images and photographs of the
				products and other data from external sources ("Third Party Content"). Similar Third Party Content
				would also be available to You on the email received by You from company. The provision of Third
				Party Content is for general informational purposes only. You acknowledge that the Third Party
				Content provided to You is obtained from sources believed to be reliable. company does not provide
				any guarantee with respect to any the Third Party Content and company shall not be held liable for
				any loss suffered by You based on Your reliance on or use of such data.</p>
				<h6>1. Disclaimer Of Warranties & Liabilities</h6>
				<p>You expressly understand and agree that, to the maximum extent permitted by applicable law:
				the website, services and other materials are provided by Company on an "as is" basis without
				warranty of any kind, express, implied, statutory or otherwise, including the implied warranties of
				title, non-infringement, merchantability or fitness for a particular purpose. without limiting the
				foregoing, Company makes no warranty that (i) the Website or the services will meet your
				requirements or your use of the Website or the services will be uninterrupted, timely, secure or
				error-free; (ii) the results that may be obtained from the use of the Website, services or materials
				will be effective, accurate or reliable; (iii) the quality of the Website, services or other materials will
				meet your expectations; or that (iv) any errors or defects in the Website, services or other materials
				will be corrected. No advice or information, whether oral or written, obtained by you from Company
				or through or from use of the services shall create any warranty not expressly stated in the terms.
				to the maximum extent permitted by applicable law, Company will have no liability related to user
				content arising under intellectual property rights, libel, privacy, publicity, obscenity or other laws.
				Company also disclaims all liability with respect to the misuse, loss, modification or unavailability of
				any user content</p>
				<p>Company will not be liable for any loss that you may incur as a consequence of unauthorized use of
				Your Account or Account information in connection with the Website or any services or materials,
				either with or without your knowledge. Company has endeavored to ensure that all the information
				on the Website is correct, but Company neither warrants nor makes any representations regarding the quality, accuracy or completeness of any data, information, product or service. Company shall
				not be responsible for the delay or inability to use the website or related functionalities, the
				provision of or failure to provide functionalities, or for any information, software, products,
				functionalities and related graphics obtained through the Website, or otherwise arising out of the
				use of the Website, whether based on contract, tort, negligence, strict liability or otherwise. further,
				Company shall not be held responsible for non-availability of the website during periodic
				maintenance operations or any unplanned suspension of access to the website that may occur due to
				technical reasons or for any reason beyond Company's control. The user understands and agrees
				that any material or data downloaded or otherwise obtained through the Website is done entirely at
				their own discretion and risk and they will be solely responsible for any damage to their computer
				systems or loss of data that results from the download of such material or data. Company is not
				responsible for any typographical error leading to an invalid coupon. Company accepts no liability
				for any errors or omissions, with respect to any information provided to you whether on behalf of
				itself or third parties.</p>
				<p>Company shall not be liable for any third party product or services. the advertisement available on email or website with respect to the third party website or the Products are for information purpose only.</p>
				<p>You expressly agree that Your use of the Website is at Your risk.</p>
				<h6>2. Indemnification and Limitation of Liability</h6>
				<p>You agree to indemnify, defend and hold harmless Company including but not limited to its affiliates,
				vendors, agents and employees from and against any and all losses, liabilities, claims, damages,
				demands, costs and expenses (including legal fees and disbursements in connection therewith and
				interest chargeable thereon) asserted against or incurred by Company that arise out of, result from,
				or may be payable by virtue of, any breach or non-performance of any representation, warranty,
				covenant or agreement made or obligation to be performed by You pursuant to these Terms.
				Further, You agree to hold Company harmless against any claims made by any third party due to, or
				arising out of, or in connection with, Your use of the Website, any claim that Your material caused
				damage to a third party, Your violation of the Terms, or Your violation of any rights of another,
				including any intellectual property rights.</p>
				<p>Notwithstanding anything to contrary, Company's entire liability to You under this Terms or
				otherweis shall be the refund of the money charged from You for any specific voucher or Product or
				service, under which the unlikely liability arises.</p>
				<p>In no event shall Company, its officers, directors, employees, partners or suppliers be liable to You,
				the vendor or any third party for any special, incidental, indirect, consequential or punitive damages
				whatsoever, including those resulting from loss of use, data or profits, whether or not foreseeable or
				whether or not Company has been advised of the possibility of such damages, or based on any theory
				of liability, including breach of contract or warranty, negligence or other tortious action, or any other
				claim arising out of or in connection with Your use of or access to the Website, services or materials.
				Company is not responsible for any non-performance or breach of any contract entered into
				between Buyers and Sellers. Company cannot and does not guarantee that the concerned Buyers
				and/or Sellers will perform any <no transactions are entered into> on the Website. Company shall
				not and is not required to mediate or resolve any dispute or disagreement between Buyers and
				Sellers.</p>
				<p>Company does not at any point of time during any transaction between Buyer and Seller on the
				Website come into or take possession of any of the products or services offered by Seller nor does it
				at any point gain title to or have any rights or claims over the products or services offered by Seller
				to Buyer</p>
				<p>It no time shall Company hold any right, title or interest over the products nor shall Company have
				any obligations or liabilities in respect of such contract entered into between Buyers and Sellers.
				Company is not responsible for unsatisfactory or delayed performance of services or damages or
				delays as a result of products which are out of stock, unavailable or back ordered.
				The limitations and exclusions in this section apply to the maximum extent permitted by applicable
				law.</p>
				<h6>3. Violation of the Terms</h6>
				<p>You agree that Company may, in its sole discretion and without prior notice, terminate Your access
				to the Website and block Your future access to the Website if Company determines that You have
				violated these Terms or Additional Terms. You also agree that any violation by You of these Terms
				will constitute an unlawful and unfair business practice, and will cause irreparable harm to Company, for which monetary damages would be inadequate, and You consent to Company
				obtaining any injunctive or equitable relief that Company deems necessary or appropriate in such
				circumstances. These remedies are in addition to any other remedies Company may have at law or in
				equity.</p>
				<p>You agree that Company may, in its sole discretion, and without prior notice, terminate Your access
				to the Website, for cause, which includes (but is not limited to): (1) requests by law enforcement or
				other government agencies; (2) a request by You (self-initiated account deletions); (3)
				discontinuance or material modification of the Website or any service offered on or through the
				Website; or (4) unexpected technical issues or problems.</p>
				<p>If Company does take any legal action against You as a result of Your violation of these Terms,
				Company will be entitled to recover from You, and You agree to pay, all reasonable attorneys' fees
				and costs of such action, in addition to any other relief granted to Company.</p>
				<h6>4. Termination</h6>
				<p>The Terms will continue to apply until terminated by either You or Company as set forth below. If
				You want to terminate Your agreement with Company, You may do so by (i) not accessing the
				Website; or (ii) closing Your accounts for all of the services that You use, where Company has made
				this option available to You.</p>
				<p>Company may, at any time, with or without notice, terminate the Terms (or portion thereof, such as any individual Additional Terms) with you if:</p>
				<p>You breach any of the provisions of the Terms, the Privacy Policy or any other terms, conditions, or
				policies that may be applicable to You from time to time (or have acted in a manner that clearly
				shows that You do not intend to, or are unable to, comply with the same);</p>
				<p>Company is required to do so by law (for example, where the provision of the services hereunder, to You is, or becomes, unlawful);</p>
				<p>The provision of the services to You, by Company is, in Company's opinion, no longer commercially viable;</p>
				<p>Company has elected to discontinue, with or without reason, access to the Website, the services (or any part thereof); or Company may also terminate or suspend all or a portion of Your account or access to the services
				with or without reason. Except as may be set forth in any Additional Terms applicable to a particular
				service, termination of Your Account may include: (i) removal of access to all offerings within the
				Website or with respect to the services; (ii) deletion of Your materials and Account Information,
				including Your personal information, log-in ID and password, and all related information, files and
				materials associated with or inside Your Account (or any part thereof); and (iii) barring of further
				use of the Services.</p>
				<p>You agree that all terminations shall be made in Company's sole discretion and that Company shall
				not be liable to You or any third party for any termination of Your Account (and accompanying
				deletion of Your Account Information), or Your access to the Website and the services offered
				thereunder.</p>
				<p>Notwithstanding the foregoing, these Terms will survive indefinitely unless and until Company chooses to terminate them.</p>
				<p>Notwithstanding the foregoing, these Terms will survive indefinitely unless and until Company chooses to terminate them.</p>
				<p>If You or Company terminates Your use of the Website, Company may delete any content or other
				materials relating to Your use of the Website and Company will have no liability to You or any third
				party for doing so.</p>
				<h6>5. Governing Law</h6>
				<p>These Terms and all transactions entered into on or through the Website and the relationship
				between You and Company shall be governed in accordance with the laws of India without reference
				to conflict of laws principles.</p>
				<p>You agree that all claims, differences and disputes arising under or in connection with or in relation
				hereto the Website, the Terms or any transactions entered into on or through the Website or the
				relationship between You and Company shall be subject to the exclusive jurisdiction of the courts at
				Mumbai, India and You hereby accede to and accept the jurisdiction of such courts.</p>
				<h6>6. Report Abuse</h6>
				<p>In the event You come across any abuse or violation of these Terms or if You become aware of any objectionable content on the Website, please report to Company’s customer support team.</p>
				<h6>7. Privacy Policy</h6>
				<p>Company views protection of Your privacy as a very important principle. We store and process Your
				Account Information including any sensitive personal / financial information collected (as defined under the Information Technology Act, 2000), if any, on computers that may be protected by
				physical as well as reasonable technological security measures and procedures in accordance with
				Information Technology Act 2000 and Rules there under. Company’s current Privacy Policy is
				available at www.drhelpdesk.in. If You object to Your Information being transferred or used in this
				way please do not use Website.</p>
				<p>Company will share / sell / transfer / license / covey some or all of your personal information with
				another business entity should we (or our assets) plan to merge with or are acquired by that
				business entity, or re-organization, amalgamation, restructuring of business or for any other reason
				whatsoever. Should such a transaction or situation occur, the other business entity or the new
				combined entity will be required to follow the privacy policy with respect to Your personal
				information. Once You provide Your information to us, You provide such information to Company
				and affiliates of Company and Company and its affiliate may use such information to provide You
				various services with respect to Your transaction whether such transaction are conducted
				on www.drhelpdesk.in or with third party merchant's or third party merchant's website.
				The User hereby consents, expresses and agrees that he has read and fully understands the Privacy
				Policy of Company in respect of the Website. You further consent that the terms and contents of such
				Privacy Policy are acceptable to You. (https://DrHelpDesk.in/privacy-policy)</p>
				<h6>8. Communications</h6>
				<p>You hereby expressly agree to receive communications by way of SMS, e-mails from Company,
				phone calls relating to the Products offered through the Website.
				A User can unsubscribe / opt-out from receiving communications from Company through SMS and email anytime by:</p>
				<p>Visiting www.drhelpdesk.into unsubscribe from messages/ SMS; and</p>
				<p>Newsletters sent daily at the registered email address:</p>
				<p>by clicking on the unsubscribe option attached at the bottom of newsletter received through e-mail</p>
				<h6>9. General Provisions</h6>
				<p>Notice: All notices of Company will be served by email or by general notification on the Website. Any
				notice provided to Company pursuant to the Terms should be sent to legal@DrHelpDesk.in
				Assignment: You cannot assign or otherwise transfer the Terms, or any rights granted hereunder to
				any third party. Company's rights under the Terms are freely transferable by Company to any third
				parties without the requirement of seeking Your consent.</p>
				<p>Severability: If, for any reason, a court of competent jurisdiction finds any provision of these Terms,
				or portion thereof, to be unenforceable, that provision shall be enforced to the maximum extent
				permissible so as to give effect to the intent of the parties as reflected by that provision, and the
				remainder of the Terms shall continue in full force and effect</p>		 		        
		    </div>
	   	</div>
   	</div>
    
</div>
<div class="block-space block-space--layout--divider-sm"></div>