@extends('main_master') 
	@section('main_content')    
	@if($flag == 1)
  		@include('UI.components/user/about_us');  
  	@elseif($flag == 2) 
  		@include('UI.components/user/privacy_policy')  
  	@elseif($flag == 3) 
  		@include('UI.components/user/contact_us') 
  	@elseif($flag == 4) 
  		@include('UI.components/user/blog')   
    @elseif($flag == 5) 
      @include('UI.components/user/refund_policy')   
    @elseif($flag == 6) 
      @include('UI.components/user/return_policy')   
    @elseif($flag == 7) 
      @include('UI.components/user/cancellation_policy')   
    @elseif($flag == 8) 
      @include('UI.components/user/term_condition')   
    @elseif($flag == 9) 
      @include('UI.components/user/disclaimer')   
    @elseif($flag == 10) 
  		@include('UI.components/user/brand') 
    @elseif($flag == 11) 
  		@include('UI.components/user/delivery_info')
    @elseif($flag == 12) 
  		@include('UI.components/user/store_location')
    @endif 
@stop 
