@extends('main_master') 
	@section('main_content')    
	@if($flag == 1)
  		@include('UI.components/user/user_profile')  
  	@elseif($flag == 2) 
  		@include('UI.components/user/user_order')  
  	@elseif($flag == 3) 
  		@include('UI.components/user/user_booking')  
  	@elseif($flag == 4) 
  		@include('UI.components/user/user_address')  
    @elseif($flag == 5) 
      @include('UI.components/user/user_change_password') 
    @elseif($flag == 6) 
      @include('UI.components/user/user_dashboard') 
    @elseif($flag == 7) 
      @include('UI.components/user/user_address_edit') 
    @elseif($flag == 8) 
      @include('UI.components/user/user_order_detail') 
  	@endif 
@stop 
